# Documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
# Documentation: https://www.npmjs.com/package/gh-pages

name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to GH-Pages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d dist --cname v2.sugarlabs.org -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}