# Documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Linting

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: Lint Code Base

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript linting
        run: npm run lint:ts

      - name: Run Markdown linting
        run: npm run lint:md

      - name: Check code formatting with Prettier
        run: npm run format:check